spring:
  datasource:
    local:
      username: greygao
      password: 271211
      url: jdbc:mysql://47.101.11.248:3306/demo1?serverTimezone=UTC&useUnicode=true@characterEncoding=utf-8
      driver-class-name: com.mysql.jdbc.Driver
      type: com.alibaba.druid.pool.DruidDataSource
    remote:
      username: greygao
      password: 271211
      url: jdbc:mysql://47.101.11.248:3306/demo2?serverTimezone=UTC&useUnicode=true@characterEncoding=utf-8
      driver-class-name: com.mysql.jdbc.Driver
      type: com.alibaba.druid.pool.DruidDataSource


server:
  port: 8083